server:
  port : 9097
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Hendra2016/config-server
          clone-on-start: true